-- Enable Row Level Security
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- Tenders Table (Active Tenders)
create table tenders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date_submitted timestamp with time zone not null, -- When it was submitted TO us
  name text not null,
  deadline timestamp with time zone not null,
  quoted_amount numeric not null,
  our_submission_date timestamp with time zone, -- When WE submitted our response
  status text check (status in ('submitted', 'pending')) default 'pending',
  description text,
  requirements text
);

-- Submitted Tenders Table (Tenders we submitted to them)
create table submitted_tenders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date_submitted timestamp with time zone not null,
  name text not null,
  deadline timestamp with time zone not null,
  document_url text,
  document_name text
);

-- Submissions Table (New requirements submitted by client)
create table requirements_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  tender_name text not null,
  deadline timestamp with time zone not null,
  description text,
  files jsonb -- Array of file metadata {name, url, size}
);

-- Contact Messages Table
create table contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  subject text not null,
  message text not null,
  status text default 'new'
);

-- App Settings (for PIN)
create table app_settings (
  key text primary key,
  value text not null
);

-- Insert default PIN (hashed or plain for now as requested, let's stick to simple comparison for prototype migration)
insert into app_settings (key, value) values ('access_pin', '1111');

-- Seed Data for Tenders
insert into tenders (date_submitted, name, deadline, quoted_amount, our_submission_date, status, description, requirements)
values
('2025-12-01', 'Government IT Infrastructure Upgrade', '2025-12-20 17:00:00+00', 2450000, '2025-12-15 14:30:00+00', 'submitted', 'Complete overhaul of government IT infrastructure including servers, networking equipment, and security systems.', 'Hardware procurement, installation, configuration, and 2-year maintenance contract.'),
('2025-11-15', 'Smart City IoT Deployment', '2025-12-18 16:00:00+00', 5800000, '2025-12-12 10:15:00+00', 'submitted', 'Deployment of IoT sensors and smart city infrastructure across metropolitan area.', 'Sensor installation, data platform setup, mobile app development, and integration with existing systems.'),
('2025-12-05', 'Healthcare Management System', '2025-12-25 18:00:00+00', 1850000, null, 'pending', 'Development and implementation of comprehensive healthcare management system for regional hospital network.', 'Custom software development, database design, staff training, and ongoing support.'),
('2025-11-28', 'Cybersecurity Assessment & Implementation', '2025-12-22 15:00:00+00', 980000, '2025-12-14 16:45:00+00', 'submitted', 'Comprehensive cybersecurity audit and implementation of security measures for financial institution.', 'Security assessment, penetration testing, firewall configuration, and employee training program.'),
('2025-12-08', 'Cloud Migration Services', '2025-12-30 17:00:00+00', 3200000, null, 'pending', 'Migration of legacy systems to cloud infrastructure with minimal downtime.', 'Cloud architecture design, data migration, application modernization, and staff training.');

-- Seed Data for Submitted Tenders
insert into submitted_tenders (date_submitted, name, deadline, document_url, document_name)
values
('2025-12-10', 'Enterprise Software Development RFP', '2025-12-28 17:00:00+00', '#', 'Enterprise_Software_RFP.pdf'),
('2025-12-08', 'Network Infrastructure Upgrade Tender', '2025-12-22 16:00:00+00', '#', 'Network_Infrastructure_Tender.pdf'),
('2025-12-12', 'Data Center Modernization Project', '2025-12-30 18:00:00+00', '#', 'DataCenter_Modernization.pdf'),
('2025-11-25', 'Cloud Security Implementation', '2025-12-20 15:00:00+00', '#', 'Cloud_Security_RFP.pdf'),
('2025-12-14', 'Mobile Application Development', '2026-01-05 17:00:00+00', '#', 'Mobile_App_Development.pdf');

-- Enable RLS
alter table tenders enable row level security;
alter table submitted_tenders enable row level security;
alter table requirements_submissions enable row level security;
alter table contact_messages enable row level security;
alter table app_settings enable row level security;

-- Policies (Public read for prototype simplicity, normally would restrict)
create policy "Allow public read access" on tenders for select using (true);
create policy "Allow public read access" on submitted_tenders for select using (true);
create policy "Allow public insert" on requirements_submissions for insert with check (true);
create policy "Allow public insert" on contact_messages for insert with check (true);
create policy "Allow public read access" on app_settings for select using (true);

-- Storage Bucket for Documents
insert into storage.buckets (id, name, public) values ('documents', 'documents', true);
create policy "Public Access" on storage.objects for select using ( bucket_id = 'documents' );
create policy "Public Upload" on storage.objects for insert with check ( bucket_id = 'documents' );

